name: test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mock AWS API
        run: |
          docker run -i -t -d -p 5000:5000 --rm --name moto motoserver/moto:5.0.15
          docker ps

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          skip_check: CKV_TF_1
          framework: terraform

      - name: Install Terraform
        run: |
          curl -L https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip -o terraform_linux_amd64.zip
          unzip terraform_linux_amd64.zip
          mv terraform /usr/local/bin
          terraform version

      - name: Test deploy
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve

      - name: Cleanup
        run: |
          terraform destroy -auto-approve
          docker rm -f moto
